# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'georefe_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(52, 152, 219);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 34, 491, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 261, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 210, 421, 21))
        self.label_3.setObjectName("label_3")
        self.georeferencer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.georeferencer_btn.setGeometry(QtCore.QRect(270, 310, 161, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.georeferencer_btn.setFont(font)
        self.georeferencer_btn.setStyleSheet("background-color:rgb(46, 204, 113);")
        self.georeferencer_btn.setObjectName("georeferencer_btn")
        self.visualiser_btn = QtWidgets.QPushButton(self.centralwidget)
        self.visualiser_btn.setGeometry(QtCore.QRect(270, 380, 161, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.visualiser_btn.setFont(font)
        self.visualiser_btn.setStyleSheet("background-color:rgb(46, 204, 113);")
        self.visualiser_btn.setObjectName("visualiser_btn")
        self.path_lidar_bf_geo_btn = QtWidgets.QPushButton(self.centralwidget)
        self.path_lidar_bf_geo_btn.setGeometry(QtCore.QRect(650, 60, 21, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.path_lidar_bf_geo_btn.setFont(font)
        self.path_lidar_bf_geo_btn.setStyleSheet("background-color:rgb(48, 110, 255);")
        self.path_lidar_bf_geo_btn.setObjectName("path_lidar_bf_geo_btn")
        self.dgps_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.dgps_path_btn.setGeometry(QtCore.QRect(650, 150, 21, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dgps_path_btn.setFont(font)
        self.dgps_path_btn.setStyleSheet("background-color:rgb(48, 110, 255);")
        self.dgps_path_btn.setObjectName("dgps_path_btn")
        self.lidar_geo_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.lidar_geo_path_btn.setGeometry(QtCore.QRect(650, 240, 21, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lidar_geo_path_btn.setFont(font)
        self.lidar_geo_path_btn.setStyleSheet("background-color:rgb(48, 110, 255);")
        self.lidar_geo_path_btn.setObjectName("lidar_geo_path_btn")
        self.path_lidar_bf_geo_txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.path_lidar_bf_geo_txt.setGeometry(QtCore.QRect(60, 60, 581, 31))
        self.path_lidar_bf_geo_txt.setStyleSheet("")
        self.path_lidar_bf_geo_txt.setObjectName("path_lidar_bf_geo_txt")
        self.dgps_path_txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.dgps_path_txt.setGeometry(QtCore.QRect(60, 150, 581, 31))
        self.dgps_path_txt.setObjectName("dgps_path_txt")
        self.lidar_geo_path_txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.lidar_geo_path_txt.setGeometry(QtCore.QRect(60, 240, 581, 31))
        self.lidar_geo_path_txt.setObjectName("lidar_geo_path_txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Selectionner le dossier contenant les fichiers lidar en format xyz"))
        self.label_2.setText(_translate("MainWindow", "Importer votre fichier DGPS"))
        self.label_3.setText(_translate("MainWindow", "Choisir l\'emplacement du fichier LIDAR géoréférencé"))
        self.georeferencer_btn.setText(_translate("MainWindow", "Géoréférencer"))
        self.visualiser_btn.setText(_translate("MainWindow", "Visualiser"))
        self.path_lidar_bf_geo_btn.setText(_translate("MainWindow", "..."))
        self.dgps_path_btn.setText(_translate("MainWindow", "..."))
        self.lidar_geo_path_btn.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
